### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 7LFB** [jonghyunlee1993/LiverFibrosisClassificationDatathon#1]
Thanks for your code sharing. Is the data public? Thanks.

**Comment by jonghyunlee1993** [comment]
Thank you for your interest. 

Unfortunately, this dataset is not available publicly. 

And I also doesn't have any ownership for this dataset.

If you have more interest for this dataset, please contact the MCMC (Medical Convergence Research Center) at Wonkwang university hospital, at the south Korea.

This is the url of MCMC.
https://www.wonmcrc.org/
(It seems that they are not provide any english language support)

**Comment by 7LFB** [comment]
many thanks!
